### PR TITLE
Tic-Tac-Toe/Milestone 2-User Interface

### PR DESCRIPTION
**Pull request by RyelBanfield**
This PR contains a basic player class and accepts some input from the users while guiding them on how to play the game.

### CODE REVIEW

**Comment by mimipeshy** [comment]
### STATUS: CHANGES REQUIRED 🔴 ♻️ 

Hello team @RyelBanfield and @Bishoy-Samwel 👋🏾 👋🏾 , great job so far in this milestone. This is a good start, but let's keep going by implementing the following

- [x] In this step students are supposed to only mock the basic flow of the game. This means implementing a user interface that displays prompts for users (print/puts) and collects user input (gets.chomp). No game logic (for example checking who is a winner) is required in this milestone - instead, students can just display "The winner is X" no matter who won. Usage of inline comments in this milestone is allowed.
* [x] `[REQUIRED]` game tells which player turn it is (without computing who the winner is)
* [x] `[REQUIRED]` game asks the player to select from available moves
* [x] `[REQUIRED]` game informs the player if the selected move is invalid (without computing what an invalid move is)
* [x] `[REQUIRED]` game displays board after the player move (without computing which spots on the board are taken)
* [x] `[REQUIRED]` game informs the player if the selected move is a winning move (without computing the winning move)
* [x] `[REQUIRED]` game informs the player if the selected move is a draw move (without computing draw)
* [x] `[REQUIRED]` game repeats all actions for the next player's move

##### Implementation details

* [x] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
* [x] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```
That's all :smile: kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, or just comment on this PR and tag my name and I will be glad to help_
Regards
Peris Ndanu

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Bishoy Faheem Saeed & Ryel Banfield** 
Good job with the improvements for this project :muscle:  :muscle:
You did a good job implementing the required changes from the previous TSE :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [x] Remove commented code
- [x] Lines 29, 30, and 31 should be outside before the while, otherwise, you are repeating these messages (about who is X and who is 0) every single turn. In the loop, you should only have the required logic for every turn.
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by mimipeshy** [comment]
### STATUS: CHANGES REQUIRED 🔴 ♻️ 

Hey, team @RyelBanfield and @Bishoy-Samwel 👋🏾 👋🏾 great job so far in this milestone. Great job on working on the changes requested. However, a few things are still pending as noted below

- [x] [REQUIRED] game informs the player if the selected move is invalid ] [Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/invalid_move.png)
- [x] Game asks the player to select from available moves. [Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/select_play.png)
* [x] Game informs player if the selected move is a winning move (without computing the winning move). [Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_win%2059.png)
* [x] Game informs player if the selected move is a draw move (without computing draw). [Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_tie.png)
* [x] Game repeats all actions for the next player's move. [Example gif](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_flow_example.gif)

That's all :smile: kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, or just comment on this PR and tag my name and I will be glad to help_
Regards
Peris Ndanu

**Comment by RyelBanfield** [comment]
We already have all of these statements without logic.

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @RyelBanfield and @Bishoy-Samwel :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [x] Your game is expected to inform players if their selected move is invalid (without computing what an invalid move is). [Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/invalid_move.png)
* [x] Your game should inform players if their selected move is a winning move (without computing the winning move). [Example screenshot]. (https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_win%2059.png). Your game displays the message every time a player makes a move which shouldn't be.
* [x] Your game should inform players if their selected move is a draw move (without computing draw). [Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_tie.png). Your game displays the message every time a player makes a move which shouldn't be.
* [x] game repeats all actions for the next player's move. [Example gif](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_flow_example.gif)

### Make the requested changes and request another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by mimipeshy** [comment]
#### STATUS: CHANGES REQUESTED 🔴 ♻️ 

Hey, team @RyelBanfield and @Bishoy-Samwel 👋🏾 👋🏾 . I really appreciate the effort that you are putting into this game but you are yet to work on some changes

- [x] Take time and open the attached examples provided to have a clear understanding of what is being required of you. 
- [x] The changes suggested have still not been implemented. Work on every one of them
- [x] [**HINT**] Your game flow should mimic this  [Example gif](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_flow_example.gif) to get your milestone approved.


If you are having problems/ questions with this milestone, don't hesitate to slack me and i will be glad to help

That's all :smile: kindly submit another review when done.

Regards
Peris Ndanu

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @RyelBanfield and @Bishoy-Samwel 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [x] Game asks the player to select from available moves. (As previous TSE suggested)
- [x] game informs the player if the selected move is a draw move (without computing draw) (As previous TSE suggested)
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by RyelBanfield** [comment]
@umairarshadbutt this is a joke, right? 

`puts 'Game Instructions: Choose a available number to place your move!'`

you're wasting our time because we don't have: 

` puts "#{player1.name} make your move: "
  move = gets.chomp
  puts 'You draw.'`

??

**Comment by umairarshadbutt** [comment]
Hi @RyelBanfield 
Sorry that my review is not completely understandable for you. I hope [this video](https://www.loom.com/share/845b457fa4064741bd67ab6ed44b0a95) will help you to understand.

Best,
Umair Arshad

**Comment by RyelBanfield** [comment]
@umairarshadbutt  The UI does not update here. 

https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_flow_example.gif

The board stays the same.

**Review by smcommits — APPROVED** [review]
# Status: Approved :+1:
Hello, team!
**Great Work!  Your code does a good job of reflecting the overall application design. 
This PR is now approved. You can go ahead and merge the branch. Congratulations and good luck with your next milestone.** 

# 
Any further questions? Please reach out to me on [slack](https://microverse-students.slack.com/team/U017N7LLZ40)

**Pull request merged**
